name: CD NCLOUD
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.NCP_DEV_SERVER_IP }}
          username: ${{ secrets.NCP_DEV_SERVER_USER }}
          password: ${{ secrets.NCP_DEV_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_DEV_SERVER_PORT }}
          script: |
            ssh was
            cd ./Time-Deal-Server
            git pull main
            ./gradlew clean build
            nohup java -jar ./build/libs/time-deal-0.0.1-SNAPSHOT.jar 1> application.log 2>&1 &